export const characteristicsAndQualities = {
  fi: [
    'Ahkera',
    'Aikaansaava',
    'Ajattelevainen',
    'Aktiivinen',
    'Aloitekykyinen',
    'Antelias',
    'Arvostelukykyinen',
    'Avarakatseinen',
    'Avulias',
    'Delegoiva',
    'Diplomaattinen',
    'Edistyksellinen',
    'Eloisa',
    'Elämänmyönteinen',
    'Eläytymiskykyinen',
    'Energinen',
    'Ennakkoluuloton',
    'Epäitsekäs',
    'Epäsiisti',
    'Epävirallinen',
    'Esiintyjä',
    'Estoton',
    'Eteenpäin pyrkivä',
    'Haastava',
    'Haasteisiin tarttuva',
    'Hallitseva',
    'Harkitseva',
    'Herkkä',
    'Herkkävaistoinen',
    'Hidas',
    'Hienostunut',
    'Hienotunteinen',
    'Hiljainen',
    'Hillitty',
    'Huolehtiva',
    'Huolellinen',
    'Huoleton',
    'Huolimaton',
    'Huoliteltu',
    'Huomaavainen',
    'Huumorintajuinen',
    'Hyvä kuuntelija',
    'Hyväntahtoinen',
    'Hyväntekijä',
    'Hyväntuulinen',
    'Iloinen',
    'Impulsiivinen',
    'Innoittava',
    'Innokas',
    'Innostava',
    'Itsensä hillitsevä',
    'Itsenäinen',
    'Itsepintainen',
    'Itsetietoinen',
    'Itsevarma',
    'Johdonmukainen',
    'Johtaja',
    'Joustava',
    'Järjestelmällinen',
    'Järkevä',
    'Karismaattinen',
    'Kaukonäköinen',
    'Kekseliäs',
    'Kestävä',
    'Kielellisesti lahjakas',
    'Kilpailuhenkinen',
    'Kiltti',
    'Kohtelias',
    'Konservatiivinen',
    'Kunnianhimoinen',
    'Kunnollinen',
    'Kurinalainen',
    'Kypsä',
    'Kyselevä',
    'Kyvykäs',
    'Kärsivällinen',
    'Kätevä',
    'Kätevä käsistään',
    'Käytännöllinen',
    'Lempeä',
    'Leppoisa',
    'Looginen',
    'Lujatahtoinen',
    'Luonnollinen',
    'Luonnonläheinen',
    'Luonnonmukainen',
    'Luonteva',
    'Luotettava',
    'Luottavainen',
    'Luova',
    'Mahdollisuuksiin tarttuva',
    'Maltillinen',
    'Mielikuvituksekas',
    'Miellyttävä',
    'Monipuolinen',
    'Monitaitoinen',
    'Mukava',
    'Myötätuntoinen',
    'Määrätietoinen',
    'Neuvokas',
    'Nokkela',
    'Nopea',
    'Nuorekas',
    'Näppärä',
    'Ohjaaja',
    'Oikeudenmukainen',
    'Oivaltava',
    'Omaperäinen',
    'Oppivainen',
    'Optimistinen',
    'Organisoiva',
    'Palveluhenkinen',
    'Peloton',
    'Persoonallinen',
    'Perusteellinen',
    'Pikkutarkka',
    'Pinnallinen',
    'Pitkäjänteinen',
    'Pitkämielinen',
    'Pohdiskeleva',
    'Puhelias',
    'Pätevä',
    'Päättäväinen',
    'Rationaalinen',
    'Rauhallinen',
    'Realistinen',
    'Rehellinen',
    'Reipas',
    'Rento',
    'Riippumaton',
    'Rohkea',
    'Sanavalmis',
    'Seikkailunhaluinen',
    'Selväsanainen',
    'Seuraaja',
    'Seurallinen',
    'Siisti',
    'Sinnikäs',
    'Sisäänpäin kääntynyt',
    'Sitoutumaton',
    'Sopeutuvainen',
    'Sopuisa',
    'Sosiaalinen',
    'Sotkuinen',
    'Spontaani',
    'Suora',
    'Suostutteleva',
    'Suunnitelmallinen',
    'Suurpiirteinen',
    'Suvaitseva',
    'Sydämellinen',
    'Sympaattinen',
    'Systemaattinen',
    'Säntillinen',
    'Säästäväinen',
    'Tahdikas',
    'Taiteellinen',
    'Taloudellinen',
    'Tarkka',
    'Tarmokas',
    'Tasainen',
    'Tasapainoinen',
    'Teeskentelemätön',
    'Tehokas',
    'Tekijä',
    'Tietäväinen',
    'Tiedonhaluinen',
    'Tieteellinen',
    'Tunnollinen',
    'Tunteellinen',
    'Turvallinen',
    'Tutkiskeleva',
    'Työnarkomaani',
    'Täsmällinen',
    'Täydellisyyden tavoittelija',
    'Ujo',
    'Ulospäin suuntautunut',
    'Urheilullinen',
    'Uskalias',
    'Uskonnollinen',
    'Uskottava',
    'Uuttera',
    'Vahva',
    'Vakaa',
    'Vakava',
    'Vakuuttava',
    'Valpas',
    'Varautunut',
    'Varovainen',
    'Vastuuntuntoinen',
    'Vilkas',
    'Vilpitön',
    'Voimakas',
    'Voimakastahtoinen',
    'Välitön',
    'Välkky',
    'Yhteistyökykyinen',
    'Yksilöllinen',
    'Ylpeä',
    'Ymmärrettävä',
    'Ymmärtäväinen',
    'Yritteliäs',
    'Yrittäjähenkinen',
    'Ystävällinen',
    'Älykäs',
    'Älyllinen',
  ],
  en: [
    'Diligent',
    'Productive',
    'Thoughtful',
    'Active',
    'Initiative',
    'Generous',
    'Judicious',
    'Open-minded',
    'Helpful',
    'Delegative',
    'Diplomatic',
    'Progressive',
    'Lively',
    'Optimistic',
    'Empathetic',
    'Energetic',
    'Unprejudiced',
    'Selfless',
    'Messy',
    'Informal',
    'Performer',
    'Uninhibited',
    'Ambitious',
    'Challenging',
    'Challenge-seeking',
    'Dominant',
    'Prudent',
    'Sensitive',
    'Intuitive',
    'Slow',
    'Sophisticated',
    'Tactful',
    'Quiet',
    'Restrained',
    'Caring',
    'Meticulous',
    'Carefree',
    'Careless',
    'Groomed',
    'Considerate',
    'Humorous',
    'Good listener',
    'Kind-hearted',
    'Benefactor',
    'Cheerful',
    'Joyful',
    'Impulsive',
    'Inspirational',
    'Eager',
    'Encouraging',
    'Self-disciplined',
    'Independent',
    'Persistent',
    'Self-aware',
    'Confident',
    'Consistent',
    'Leader',
    'Flexible',
    'Organized',
    'Sensible',
    'Charismatic',
    'Visionary',
    'Creative',
    'Durable',
    'Linguistically talented',
    'Competitive',
    'Kind',
    'Polite',
    'Conservative',
    'Ambitious',
    'Respectable',
    'Disciplined',
    'Mature',
    'Inquisitive',
    'Capable',
    'Patient',
    'Handy',
    'Skilled with hands',
    'Practical',
    'Gentle',
    'Easy-going',
    'Logical',
    'Strong-willed',
    'Natural',
    'Nature-loving',
    'Organic',
    'Unpretentious',
    'Reliable',
    'Trusting',
    'Creative',
    'Opportunity-seeking',
    'Moderate',
    'Imaginative',
    'Pleasant',
    'Versatile',
    'Multitalented',
    'Nice',
    'Compassionate',
    'Determined',
    'Resourceful',
    'Witty',
    'Quick',
    'Youthful',
    'Nimble',
    'Director',
    'Just',
    'Insightful',
    'Original',
    'Quick learner',
    'Optimistic',
    'Organized',
    'Service-minded',
    'Fearless',
    'Personable',
    'Thorough',
    'Precise',
    'Superficial',
    'Perseverant',
    'Long-suffering',
    'Reflective',
    'Talkative',
    'Competent',
    'Resolute',
    'Rational',
    'Calm',
    'Realistic',
    'Honest',
    'Energetic',
    'Relaxed',
    'Independent',
    'Brave',
    'Witty',
    'Adventurous',
    'Clear',
    'Follower',
    'Sociable',
    'Neat',
    'Persistent',
    'Introverted',
    'Non-committed',
    'Adaptable',
    'Peaceful',
    'Sociable',
    'Messy',
    'Spontaneous',
    'Direct',
    'Persuasive',
    'Planned',
    'Liberal',
    'Tolerant',
    'Warm-hearted',
    'Sympathetic',
    'Systematic',
    'Punctual',
    'Frugal',
    'Tactful',
    'Artistic',
    'Economic',
    'Precise',
    'Vigorous',
    'Even-tempered',
    'Balanced',
    'Sincere',
    'Efficient',
    'Doer',
    'Knowledgeable',
    'Inquisitive',
    'Scientific',
    'Conscientious',
    'Emotional',
    'Safe',
    'Inquisitive',
    'Workaholic',
    'Punctual',
    'Perfectionist',
    'Shy',
    'Outgoing',
    'Athletic',
    'Daring',
    'Religious',
    'Credible',
    'Industrious',
    'Strong',
    'Stable',
    'Serious',
    'Convincing',
    'Alert',
    'Reserved',
    'Cautious',
    'Responsible',
    'Vivid',
    'Sincere',
    'Powerful',
    'Strong-willed',
    'Spontaneous',
    'Bright',
    'Cooperative',
    'Individualistic',
    'Proud',
    'Comprehensible',
    'Understanding',
    'Entrepreneurial',
    'Business-minded',
    'Friendly',
    'Intelligent',
    'Intellectual',
  ],
  sv: [
    'Flitig',
    'Produktiv',
    'Eftertänksam',
    'Aktiv',
    'Initiativrik',
    'Generös',
    'Omdömesgill',
    'Öppensinnad',
    'Hjälpsam',
    'Delegerande',
    'Diplomatisk',
    'Progressiv',
    'Livlig',
    'Optimistisk',
    'Empatisk',
    'Energisk',
    'Fördomsfri',
    'Osjälvisk',
    'Rörig',
    'Informell',
    'Presterande',
    'Ohämmad',
    'Ambitiös',
    'Utmanande',
    'Utmaningssökande',
    'Dominant',
    'Försiktig',
    'Känslig',
    'Intuitiv',
    'Långsam',
    'Sofistikerad',
    'Taktfull',
    'Tyst',
    'Återhållsam',
    'Omhändertagande',
    'Noggrann',
    'Sorglös',
    'Vårdslös',
    'Välvårdad',
    'Hänsynsfull',
    'Humoristisk',
    'God lyssnare',
    'Godhjärtad',
    'Välgörare',
    'Glad',
    'Munter',
    'Impulsiv',
    'Inspirerande',
    'Ivrig',
    'Uppmuntrande',
    'Självdisciplinerad',
    'Självständig',
    'Ihärdig',
    'Självmedveten',
    'Självsäker',
    'Konsekvent',
    'Ledare',
    'Flexibel',
    'Organiserad',
    'Förnuftig',
    'Karismatisk',
    'Visionär',
    'Kreativ',
    'Uthållig',
    'Språkbegåvad',
    'Tävlingsinriktad',
    'Snäll',
    'Artig',
    'Konservativ',
    'Ambitiös',
    'Respektabel',
    'Disciplinerad',
    'Mogen',
    'Vetgirig',
    'Kompetent',
    'Tålmodig',
    'Händig',
    'Fingerfärdig',
    'Praktisk',
    'Mild',
    'Lättsam',
    'Logisk',
    'Viljestark',
    'Naturlig',
    'Naturälskande',
    'Ekologisk',
    'Anspråkslös',
    'Pålitlig',
    'Tillitsfull',
    'Kreativ',
    'Möjlighetssökande',
    'Måttlig',
    'Fantasifull',
    'Trevlig',
    'Mångsidig',
    'Mångbegåvad',
    'Trevlig',
    'Medkännande',
    'Beslutsam',
    'Resursfull',
    'Kvicktänkt',
    'Snabb',
    'Ungdomlig',
    'Vig',
    'Ledare',
    'Rättvis',
    'Insiktsfull',
    'Original',
    'Snabblärd',
    'Optimistisk',
    'Organiserad',
    'Serviceinriktad',
    'Orädd',
    'Personlig',
    'Grundlig',
    'Exakt',
    'Ytlig',
    'Uthållig',
    'Tålmodig',
    'Reflekterande',
    'Pratsam',
    'Kompetent',
    'Beslutsam',
    'Rationell',
    'Lugn',
    'Realistisk',
    'Ärlig',
    'Energisk',
    'Avslappnad',
    'Självständig',
    'Modig',
    'Kvick',
    'Äventyrlig',
    'Tydlig',
    'Följare',
    'Sällskaplig',
    'Prydlig',
    'Envis',
    'Introvert',
    'Oengagerad',
    'Anpassningsbar',
    'Fridfull',
    'Sällskaplig',
    'Rörig',
    'Spontan',
    'Direkt',
    'Övertygande',
    'Planerad',
    'Liberal',
    'Tolerant',
    'Varmhjärtad',
    'Sympatisk',
    'Systematisk',
    'Punktlig',
    'Sparsam',
    'Taktfull',
    'Konstnärlig',
    'Ekonomisk',
    'Exakt',
    'Kraftfull',
    'Jämn i humöret',
    'Balanserad',
    'Uppriktig',
    'Effektiv',
    'Handlingskraftig',
    'Kunnig',
    'Nyfiken',
    'Vetenskaplig',
    'Samvetsgrann',
    'Känslomässig',
    'Trygg',
    'Vetgirig',
    'Arbetsnarkomam',
    'Punktlig',
    'Perfektionist',
    'Blyg',
    'Utåtriktad',
    'Atletisk',
    'Djärv',
    'Religiös',
    'Trovärdig',
    'Flitig',
    'Stark',
    'Stabil',
    'Allvarlig',
    'Övertygande',
    'Alert',
    'Reserverad',
    'Försiktig',
    'Ansvarsfull',
    'Levande',
    'Uppriktig',
    'Kraftfull',
    'Viljestark',
    'Spontan',
    'Intelligent',
    'Samarbetsvillig',
    'Individualistisk',
    'Stolt',
    'Begriplig',
    'Förstående',
    'Företagsam',
    'Affärsinriktad',
    'Vänlig',
    'Intelligent',
    'Intellektuell',
  ],
};

export const importantInLife = {
  fi: [
    'Ajantasaisuus',
    'Ajattelevuus',
    'Ammatillisuus',
    'Ansioituminen',
    'Anteliaisuus',
    'Asiantuntijuus',
    'Avoimuus',
    'Demokraattisuus',
    'Dynaamisuus',
    'Eheys',
    'Eleganssi',
    'Elinvoima',
    'Epäitsekkyys',
    'Erinomaisuus',
    'Haasteet',
    'Hallinta',
    'Harkitsevaisuus',
    'Hartaus',
    'Hauskanpito',
    'Herkkyys',
    'Hienotunteisuus',
    'Hilpeys',
    'Huolellisuus',
    'Hurskaus',
    'Hyvyys',
    'Hyvä kunto',
    'Hyödyllisyys',
    'Ilmaiseminen',
    'Ilo',
    'Innostus',
    'Intuitio',
    'Isänmaallisuus',
    'Itsekontrolli',
    'Itseluottamus',
    'Itsensä toteuttaminen',
    'Itsenäisyys',
    'Jatkuva parantaminen',
    'Jatkuvuus',
    'Johonkin kuuluminen',
    'Johtajuus',
    'Jämäkkyys',
    'Jännitys',
    'Järjestys',
    'Kasvu',
    'Keskittyminen',
    'Kiitollisuus',
    'Kilpailuhenkisyys',
    'Kohteliaisuus',
    'Kohtuullisuus',
    'Kokonaisvaltaisuus',
    'Kontrolli',
    'Korkea laatu',
    'Kova työnteko',
    'Kunnia',
    'Kunnianhimo',
    'Kurinalaisuus',
    'Kätevyys',
    'Käytännöllisyys',
    'Lojaalisuus',
    'Luotettavuus',
    'Luovuus',
    'Uuden löytäminen',
    'Menestys',
    'Merkityksellisyys',
    'Monimuotoisuus',
    'Muiden palveleminen',
    'Myötätunto',
    'Määrätietoisuus',
    'Nautinto',
    'Neuvokkuus',
    'Nokkeluus',
    'Nopeus',
    'Näkemyksellisyys',
    'Nöyryys',
    'Oikeudenmukaisuus',
    'Olla paras',
    'Omaperäisyys',
    'Omistautuminen',
    'Onnellisuus',
    'Osallistuminen',
    'Perhekeskeisyys',
    'Perinteikkyys',
    'Perintö',
    'Perusteellisuus',
    'Pidättyväisyys',
    'Positiivisuus',
    'Pysyvyys',
    'Päättäväisyys',
    'Rakenne',
    'Rakkaus',
    'Rankkuus',
    'Rehellisyys',
    'Riippuvaisuus',
    'Rohkeus',
    'Seikkailunhalu',
    'Selväjärkisyys',
    'Sisäinen harmonia',
    'Spontaanisuus',
    'Status',
    'Strategisuus',
    'Sujuvuus',
    'Suvaitsevaisuus',
    'Sääntöjen noudattaminen',
    'Taloudellisuus',
    'Tarkkuus',
    'Tasa-arvo',
    'Tasapaino',
    'Tehokkuus',
    'Terveys',
    'Tiedonhalu',
    'Tiimityö',
    'Totuudellisuus',
    'Tukeminen',
    'Tuloshakuisuus',
    'Turvallisuus',
    'Tyyneys',
    'Tyytyväisyys',
    'Täydellisyys',
    'Usko',
    'Uskollisuus',
    'Uteliaisuus',
    'Vahvuus',
    'Vaikuttavuus',
    'Valmistautuminen',
    'Vapaus',
  ],
  en: [
    'Timeliness',
    'Thoughtfulness',
    'Professionalism',
    'Distinguishment',
    'Generosity',
    'Expertise',
    'Openness',
    'Democracy',
    'Dynamism',
    'Wholeness',
    'Elegance',
    'Vitality',
    'Selflessness',
    'Excellence',
    'Challenges',
    'Command',
    'Circumspection',
    'Devoutness',
    'Fun',
    'Sensitivity',
    'Discretion',
    'Cheerfulness',
    'Diligence',
    'Piety',
    'Goodness',
    'Good condition',
    'Usefulness',
    'Expression',
    'Joy',
    'Enthusiasm',
    'Intuition',
    'Patriotism',
    'Self-Control',
    'Self-Confidence',
    'Self-Actualisation',
    'Independence',
    'Continuous improvement',
    'Continuity',
    'Belonging to something',
    'Leadership',
    'Steadfastness',
    'Excitement',
    'Order',
    'Growth',
    'Focus',
    'Gratitude',
    'Competitiveness',
    'Courtesy',
    'Moderation',
    'Comprehensiveness',
    'Control',
    'High quality',
    'Hard work',
    'Honour',
    'Ambition',
    'Discipline',
    'Convenience',
    'Practicality',
    'Loyalty',
    'Reliability',
    'Creativity',
    'Discovering new things',
    'Success',
    'Relevance',
    'Diversity',
    'Serving others',
    'Compassion',
    'Determination',
    'Pleasure',
    'Resourcefulness',
    'Wit',
    'Speed',
    'Visionary',
    'Humility',
    'Fairness',
    'Being the best',
    'Originality',
    'Dedication',
    'Happiness',
    'Participation',
    'Family orientation',
    'Traditionalism',
    'Legacy',
    'Thoroughness',
    'Reticence',
    'Positivity',
    'Permanence',
    'Perseverance',
    'Structure',
    'Love',
    'Toughness',
    'Honesty',
    'Dependence',
    'Courage',
    'Adventurousness',
    'Sober-mindedness',
    'Inner harmony',
    'Spontaneity',
    'Status',
    'Strategic',
    'Smoothness',
    'Tolerance',
    'Observing the rules',
    'Economical',
    'Accuracy',
    'Equality',
    'Balance',
    'Efficiency',
    'Health',
    'Thirst for knowledge',
    'Teamwork',
    'Truthfulness',
    'Supportiveness',
    'Result-orientation',
    'Security',
    'Calmness',
    'Satisfaction',
    'Perfection',
    'Faith',
    'Faithfulness',
    'Curiosity',
    'Strength',
    'Impact',
    'Preparedness',
    'Freedom',
    'Learning new things',
    'Work',
    'Something else',
  ],
  sv: [
    'Aktualitet',
    'Betänksamhet',
    'Professionalism',
    'Meriter',
    'Generositet',
    'Expertis',
    'Öppenhet',
    'Demokrati',
    'Dynamik',
    'Integritet',
    'Elegans',
    'Livskraft',
    'Osjälviskhet',
    'Förträfflighet',
    'Utmaningar',
    'Kontroll',
    'Eftertänksamhet',
    'Flitighet',
    'Skoj',
    'Känslighet',
    'Finkänslighet',
    'Munterhet',
    'Ordentlighet',
    'Gudfruktighet',
    'Godhet',
    'God kondition',
    'Nyttighet',
    'Uttrycksfullhet',
    'Glädje',
    'Entusiasm',
    'Intuition',
    'Patriotism',
    'Självkontroll',
    'Självförtroende',
    'Självförverkligande',
    'Självständighet',
    'Kontinuerlig förbättring',
    'Kontinuitet',
    'Tillhörighet',
    'Ledarskap',
    'Beslutsamhet',
    'Spänning',
    'Ordning',
    'Tillväxt',
    'Koncentration',
    'Tacksamhet',
    'Tävlingsinstinkt',
    'Artighet',
    'Måttfullhet',
    'Inriktning på helheten',
    'Kontroll',
    'Hög kvalitet',
    'Hårt arbete',
    'Heder',
    'Ambition',
    'Disciplin',
    'Behändighet',
    'Praktiskhet',
    'Lojalitet',
    'Pålitlighet',
    'Kreativitet',
    'Upptäcka nya saker',
    'Framgång',
    'Relevans',
    'Mångformighet',
    'Tjäna andra',
    'Medkänsla',
    'Målmedvetenhet',
    'Njutning',
    'Resursfullhet',
    'Fyndighet',
    'Snabbhet',
    'Insiktsfullhet',
    'Ödmjukhet',
    'Rättvishet',
    'Att vara bäst',
    'Originalitet',
    'Hängivenhet',
    'Lycka',
    'Delaktighet',
    'Familjeorientering',
    'Traditionalism',
    'Arv',
    'Grundlighet',
    'Återhållsamhet',
    'Positivitet',
    'Beständighet',
    'Bestämdhet',
    'Struktur',
    'Kärlek',
    'Tuffhet',
    'Ärlighet',
    'Beroende',
    'Mod',
    'Äventyrslust',
    'Klartänkthet',
    'Inre harmoni',
    'Spontanitet',
    'Status',
    'Strategiskhet',
    'Smidighet',
    'Tolerans',
    'Att följa reglerna',
    'Sparsamhet',
    'Noggrannhet',
    'Jämlikhet',
    'Balans',
    'Effektivitet',
    'Hälsa',
    'Kunskapstörst',
    'Teamwork',
    'Sanningsenlighet',
    'Stöttande',
    'Resultatorientering',
    'Säkerhet',
    'Lugn',
    'Tillfredsställelse',
    'Fullständighet',
    'Tro',
    'Trohet',
    'Nyfikenhet',
    'Styrka',
    'Effektfullhet',
    'Beredskap',
    'Frihet',
    'Lära sig nya saker',
    'Arbete',
    'Något annan',
  ],
};

export const thingsAndResources = {
  fi: [
    'Työ',
    'Tuki',
    'Lukeminen',
    'Itsensä ylittäminen',
    'Lepääminen',
    'Odotukset',
    'Läheiset',
    'Keskustelut',
    'Terveys',
    'Yllätykset',
    'Urheilu',
    'Aloittaminen',
    'Perhe',
    'Sarjat ja elokuvat',
    'Suunnitelmat',
    'Juhlat',
    'Luovuus',
    'Pysähtyminen',
    'Uutiset',
    'Rauhoittuminen',
    'Itsenäisyys',
    'Luonto',
    'Musiikki',
    'Ystävät ja tuttavat',
    'Opiskelun ja muun elämän yhdistäminen',
    'Vastuu',
    'Tunteet',
    'Toimeentulo',
    'Tapahtumat',
    'Haaveilu',
    'Arki',
    'Ihmiset',
    'Hyvinvointi',
    'Pelit',
    'Eläimet',
    'Yksinolo',
    'Liikkuminen',
    'Ajankäyttö',
    'Tutustuminen',
    'Ryhmä',
    'Vapaus',
    'Vauhdikkuus',
    'Some',
    'Yhteisöllisyys',
    'Uudet tilanteet',
    'Harrastukset',
    'Oma koti',
    'Loma',
    'Kotityöt',
    'Taide ja kulttuuri',
    'Toisten auttaminen',
    'Huumori',
    'Unelmat',
    'Ravinto',
    'Hyvän huomaaminen',
    'Myötätunto',
    'Opiskelu',
    'Joku muu',
  ],
  en: [
    'Work',
    'Support',
    'Reading',
    'Exceeding yourself',
    'Resting',
    'Expectations',
    'Loved ones',
    'Conversations',
    'Health',
    'Surprises',
    'Exercise',
    'Getting started',
    'Family',
    'Series and movies',
    'Plans',
    'Parties',
    'Creativity',
    'Stopping',
    'News',
    'Calming down',
    'Independence',
    'Nature',
    'Music',
    'Friends and acquaintances',
    'Combining studies and life',
    'Responsibility',
    'Emotions',
    'Livelihood',
    'Events',
    'Dreaming',
    'Everyday life',
    'People',
    'Wellbeing',
    'Games',
    'Animals',
    'Being alone',
    'Movement',
    'Use of time',
    'Getting to know someone',
    'Group',
    'Freedom',
    'Action',
    'Social media',
    'Community',
    'New situations',
    'Hobbies',
    'Home',
    'Holiday',
    'Chores',
    'Art and culture',
    'Helping others',
    'Humour',
    'Dreams',
    'Nutrition',
    'Seeing the good',
    'Compassion',
    'Studying',
    'Something else',
  ],
  sv: [
    'Arbete',
    'Stöd',
    'Läsning',
    'Att övervinna sig själv',
    'Vila',
    'Förväntningar',
    'Närstående',
    'Diskussioner',
    'Hälsa',
    'Överraskningar',
    'Idrott',
    'Att komma igång',
    'Familj',
    'Serier och filmer',
    'Planer',
    'Fester',
    'Kreativitet',
    'Att stanna upp',
    'Nyheter',
    'Att lugna ner sig',
    'Självständighet',
    'Natur',
    'Musik',
    'Vänner och bekanta',
    'Att kombinera studier och annat liv',
    'Ansvar',
    'Känslor',
    'Att klara sig',
    'Händelser',
    'Drömmar',
    'Vardagsliv',
    'Människor',
    'Välbefinnande',
    'Spel',
    'Djur',
    'Att vara ensam',
    'Motion',
    'Tidsanvändning',
    'Nya bekantskaper',
    'Grupp',
    'Frihet',
    'Livlighet',
    'Sociala medier',
    'Samhörighet',
    'Nya situationer',
    'Hobbyer',
    'Eget hem',
    'Semester',
    'Hushållssysslor',
    'Konst och kultur',
    'Att hjälpa andra',
    'Humor',
    'Drömmar',
    'Kost',
    'Att se det goda',
    'Medkänsla',
    'Studier',
    'Något annat',
  ],
};

export const workLife = {
  fi: [
    'Osa-aikatyö',
    'Kokoaikainen työ',
    'Määräaikainen työ',
    'Freelancer-työ',
    'Nollasopimus',
    'Vuokratyö',
    'Yrittäjyys',
    'Palkkani tulee useasta eri työstä',
    'Olen valmis vaihtamaan ammattia elämäni aikana',
    'Jatkuva osaamisen päivittäminen',
    'Monilukutaito',
    'Monikielitaito',
    'Monipuoliset digitaidot',
    'Robotiikkaan liittyvä osaaminen',
    'Itsensä työllistäminen',
    'Kansainvälisyys',
    'Haluan huomioida ympäristötekijät työssäni',
    'Netin kautta tehtävä työ',
    'Työn sisällöllä ei väliä kunhan on työtä',
    'Oman ammattitaidon myyminen',
    'Työn perässä täytyy muuttaa asuinpaikkaa',
    'Oppimaan oppimisen taitojen päivittäminen',
  ],
  en: [
    'Part-time work',
    'Full-time work',
    'Fixed-term work',
    'Freelance work',
    'Zero-hour contract',
    'Agency contracts',
    'Entrepreneurship',
    'My salary comes from several jobs',
    'I am willing to change my profession in my lifetime',
    'Continuous updating of skills',
    'Multiliteracy',
    'Multilingual',
    'Versatile digital skills',
    'Robotics skills',
    'Self-employment',
    'Internationalisation',
    'I want to consider environmental factors in my work',
    'Online work',
    'Does not matter what the job is as long as there is work',
    'Selling my skills',
    'To get a job I have to move somewhere else',
    'To learn',
    'Updating my learning skills',
  ],
  sv: [
    'Deltidsarbete',
    'Heltidsarbete',
    'Tidsbegränsat arbete',
    'Frilansarbete',
    'Nollavtal',
    'Hyrt arbete',
    'Entreprenörskap',
    'Min lön kommer från flera olika jobb',
    'Jag är villig att byta yrke under min livstid',
    'Kontinuerlig uppdatering av kompetensen',
    'Multilitteracitet',
    'Mångspråkighet',
    'Mångsidiga digitala färdigheter',
    'Kompetens inom robotik',
    'Egenföretagande',
    'Internationalisering',
    'Jag vill ta hänsyn till miljöfaktorer i mitt arbete',
    'Online-arbete',
    'Arbetets innehåll spelar ingen roll så länge det finns arbete',
    'Sälja min kompetens',
    'Flytt till en annan ort på grund av jobb',
    'Uppdatering av mina inlärningsfärdigheter',
  ],
};

export const statementsOfStrength = {
  fi: [
    'Olen kohtelias.',
    'Huomioin muut ihmiset.',
    'Olen luotettava.',
    'Pidän lupaukseni.',
    'Neuvottelen, jos joudun perumaan lupaukseni.',
    'Esittäydyn ensimmäisen kerran kohdatessa.',
    'Annan kaikille suunvuoron.',
    'Kerron oman mielipiteeni.',
    'Kunnioitan muiden mielipiteitä.',
    'Huolehdin omalta osaltani kivasta työilmapiiristä.',
    'Kuuntelen aktiivisesti keskustelukumppaniani.',
    'Osoitan kiinnostusta keskustelukumppanin sanomisiin.',
    'Osaan ilmaista itseäni selkeästi ja ymmärrettävästi.',
    'Otan huomioon keskustelukumppanini tunteet ja näkökulmat.',
    'Osaan osoittaa empatiaa tarvittaessa.',
    'Käytän positiivista ja rakentavaa kieltä .',
    'Vältän puheessani negatiivisia tai loukkaavia ilmaisuja.',
    'Pidän yllä katsekontaktia.',
    'Käytän kehonkieltä tukemaan sanallista viestintääni.',
    'Annan keskustelukumppanilleni tilaa puhua ja en keskeytä häntä.',
    'Pyrin ratkaisemaan mahdolliset erimielisyydet rakentavasti.',
    'Olen valmis oppimaan ja kehittymään vuorovaikutustaidoissani.',
    'Kunnioitan keskustelukumppanini mielipiteitä, vaikka ne eroaisivat omistani.',
    'Pyrin luomaan luottamuksellisen ja avoimen ilmapiirin',
  ],
  en: [
    'I am polite.',
    'I am considerate of other people.',
    'I am trustworthy.',
    'I keep my promises.',
    'I will negotiate if I have to go back on my promise.',
    'I introduce myself the first time I meet someone.',
    'I give everyone a chance to speak.',
    'I express my opinion.',
    'I respect the opinions of others.',
    'I play my part in creating a nice working atmosphere.',
    'I actively listen to my discussion partner.',
    'I show interest in what the other person is saying.',
    'I can express myself clearly and understandably.',
    'I take into account the feelings and perspectives of my discussion partner.',
    'I can show empathy when needed.',
    'I use positive and constructive language.',
    'I avoid using negative or offensive language.',
    'I maintain eye contact.',
    'I use body language to support my verbal communication.',
    'I give the other person space to speak and will not interrupt them.',
    'I try to resolve any disagreements constructively.',
    'I am willing to learn and develop my interpersonal skills.',
    "I respect my interlocutor's opinions, even if they differ from my own. I strive to create an atmosphere of trust and openness.",
  ],
  sv: [
    'Jag är artig.',
    'Jag tar andra människor i beaktande.',
    'Jag är pålitlig.',
    'Jag håller vad jag lovar.',
    'Jag förhandlar om jag måste ta tillbaka mitt löfte.',
    'Jag presenterar mig första gången jag träffar någon.',
    'Jag ger alla muntur.',
    'Jag berättar min egen åsikt.',
    'Jag respekterar andras åsikter.',
    'Jag bidrar till att skapa ett trevligt arbetsklimat.',
    'Jag lyssnar aktivt på min samtalspartner.',
    'Jag visar intresse för vad den andra personen säger.',
    'Jag kan uttrycka mig tydligt och begripligt.',
    'Jag tar hänsyn till min samtalspartners känslor och perspektiv.',
    'Jag kan visa empati när det behövs.',
    'Jag använder ett positivt och konstruktivt språk.',
    'Jag undviker att använda ett negativt eller stötande språk.',
    'Jag håller ögonkontakt.',
    'Jag använder kroppsspråk för att stödja min verbala kommunikation.',
    'Jag ger min samtalspartner utrymme att tala och avbryter inte.',
    'Jag försöker lösa eventuella meningsskiljaktigheter på ett konstruktivt sätt.',
    'Jag är villig att lära mig och utveckla mina interaktionsfärdigheter.',
    'Jag respekterar min samtalspartners åsikter, även om de skiljer sig från mina egna.',
    'Jag strävar efter att skapa en atmosfär som präglas av förtroende och öppenhet.',
  ],
};
